name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  upload:
    name: Extract archive and create directories
    uses: appleboy/ssh-action@master
    env:
      GITHUB_SHA: ${{ github.sha }}
    with:
      host: ${{ secrets.SERVER_HOSTNAME }}
      username: kuzuru
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: 22
      script: |
        cd notifier
        wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
        sudo ./run-bot-linux.sh