name: Remote SSH Build

on:
  push:
    branches: [ main ]

jobs:
  docker:
    name: Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            kuzuru/notifier-bot-app:latest

  build:
    name: Start Bot on Server
    needs: docker
    runs-on: ubuntu-latest
    
    steps:
      - name: Restarting Docker
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          command: |
            cd /home/kuzuru/notifier
            if [[ -f "run-bot-linux.sh" ]]; then rm -rf run-bot-linux.sh fi
            wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
            chmod +x run-bot-linux.sh
            sudo docker-compose down
            sudo ./run-bot-linux.sh
