name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  upload:
    name: Uploading
    uses: appleboy/ssh-action@v0.1.6
    with:
      host: ${{ secrets.SERVER_HOSTNAME }}
      username: kuzuru
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: 22
      script: |
        whoami
        ls -al
        ls -laFh
        cd notifier
        wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
        sudo ./run-bot-linux.sh