name: Remote SSH Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Executing Remote SSH
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Atomic Deploy
      run: |
          wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
          chmod +x+x+x run-bot-linux.sh
          sudo ./run-bot-linux.sh
