name: Remote SSH Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Executing Remote SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
          chmod +x+x+x run-bot-linux.sh
          sudo ./run-bot-linux.sh
