name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using password
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          user: kuzuru
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
              whoami
              ls -al
              ls -laFh
              cd notifier
              wget https://github.com/Kuzuru/notifier-bot/releases/download/runner/run-bot-linux.sh
              sudo ./run-bot-linux.sh
            
