on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reformat-code:
    name: Reformat code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          githubToken: ${{ secrets.TOKEN }}
          args: "--skip-sorting-imports --replace"