name: "Reformat code"

on:
  push:
    branches:
      - main
      - feat/ci-cd
  pull_request:
    branches:
      - main

jobs:
  reformat-code:
    name: "Reformat code"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
      - uses: actions/checkout@v3

      - name: "Formatting code"
      - uses: axel-op/googlejavaformat-action@v3