on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reformat-code:
    name: Reformat code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: temurin
          cache: maven

      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"